# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Blog"
  url = "/post"
  weight = 10
  
[[main]]
  name = "Geografía"
  url = "/project/geografia"
  weight = 20

[[main]]
  name = "Geocomputación"
  url = "/project/geocomputation"
  weight = 30
  
  [[main]]
  name = "Geomática"
  url = "/project/geomatica"
  weight = 40

[[main]]
  name = "CV"
  url = "https://barja8.github.io/myCv/myCV.html"
  weight = 50

[[main]]
  parent = "Cursos"
  name = "QGIS"
  url = "https://barja8.github.io/CursoQGIS3.X/Sesion001/Slide.html" 
  weight = 50

[[main]]
  parent = "Cursos"
  name = "SAGAGIS"
  url = "https://barja8.github.io/SAGAcourse/Lecci%C3%B3n03_04/slides.html" 
  weight = 50

[[main]]
  name = "Research"
  url = "/research/spatial-statistic"
  weight = 40



